/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.training.mms.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.training.mms.model.Movie;
import com.training.mms.model.MovieModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Movie service. Represents a row in the &quot;movies&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MovieModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MovieImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MovieImpl
 * @generated
 */
@JSON(strict = true)
public class MovieModelImpl extends BaseModelImpl<Movie> implements MovieModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a movie model instance should use the <code>Movie</code> interface instead.
	 */
	public static final String TABLE_NAME = "movies";

	public static final Object[][] TABLE_COLUMNS = {
		{"movieId", Types.BIGINT}, {"movieName", Types.VARCHAR},
		{"directorName", Types.VARCHAR}, {"yearReleased", Types.VARCHAR},
		{"actorName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("movieId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("movieName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("directorName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("yearReleased", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("actorName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table movies (movieId LONG not null primary key,movieName VARCHAR(75) null,directorName VARCHAR(75) null,yearReleased VARCHAR(75) null,actorName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table movies";

	public static final String ORDER_BY_JPQL = " ORDER BY movie.movieId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY movies.movieId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MOVIEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public MovieModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _movieId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMovieId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _movieId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Movie.class;
	}

	@Override
	public String getModelClassName() {
		return Movie.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Movie, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Movie, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Movie, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Movie)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Movie, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Movie, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Movie)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Movie, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Movie, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Movie, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Movie, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Movie, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Movie, Object>>();
		Map<String, BiConsumer<Movie, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Movie, ?>>();

		attributeGetterFunctions.put("movieId", Movie::getMovieId);
		attributeSetterBiConsumers.put(
			"movieId", (BiConsumer<Movie, Long>)Movie::setMovieId);
		attributeGetterFunctions.put("movieName", Movie::getMovieName);
		attributeSetterBiConsumers.put(
			"movieName", (BiConsumer<Movie, String>)Movie::setMovieName);
		attributeGetterFunctions.put("directorName", Movie::getDirectorName);
		attributeSetterBiConsumers.put(
			"directorName", (BiConsumer<Movie, String>)Movie::setDirectorName);
		attributeGetterFunctions.put("yearReleased", Movie::getYearReleased);
		attributeSetterBiConsumers.put(
			"yearReleased", (BiConsumer<Movie, String>)Movie::setYearReleased);
		attributeGetterFunctions.put("actorName", Movie::getActorName);
		attributeSetterBiConsumers.put(
			"actorName", (BiConsumer<Movie, String>)Movie::setActorName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMovieId() {
		return _movieId;
	}

	@Override
	public void setMovieId(long movieId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_movieId = movieId;
	}

	@JSON
	@Override
	public String getMovieName() {
		if (_movieName == null) {
			return "";
		}
		else {
			return _movieName;
		}
	}

	@Override
	public void setMovieName(String movieName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_movieName = movieName;
	}

	@JSON
	@Override
	public String getDirectorName() {
		if (_directorName == null) {
			return "";
		}
		else {
			return _directorName;
		}
	}

	@Override
	public void setDirectorName(String directorName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_directorName = directorName;
	}

	@JSON
	@Override
	public String getYearReleased() {
		if (_yearReleased == null) {
			return "";
		}
		else {
			return _yearReleased;
		}
	}

	@Override
	public void setYearReleased(String yearReleased) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_yearReleased = yearReleased;
	}

	@JSON
	@Override
	public String getActorName() {
		if (_actorName == null) {
			return "";
		}
		else {
			return _actorName;
		}
	}

	@Override
	public void setActorName(String actorName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_actorName = actorName;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Movie.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Movie toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Movie>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MovieImpl movieImpl = new MovieImpl();

		movieImpl.setMovieId(getMovieId());
		movieImpl.setMovieName(getMovieName());
		movieImpl.setDirectorName(getDirectorName());
		movieImpl.setYearReleased(getYearReleased());
		movieImpl.setActorName(getActorName());

		movieImpl.resetOriginalValues();

		return movieImpl;
	}

	@Override
	public Movie cloneWithOriginalValues() {
		MovieImpl movieImpl = new MovieImpl();

		movieImpl.setMovieId(this.<Long>getColumnOriginalValue("movieId"));
		movieImpl.setMovieName(
			this.<String>getColumnOriginalValue("movieName"));
		movieImpl.setDirectorName(
			this.<String>getColumnOriginalValue("directorName"));
		movieImpl.setYearReleased(
			this.<String>getColumnOriginalValue("yearReleased"));
		movieImpl.setActorName(
			this.<String>getColumnOriginalValue("actorName"));

		return movieImpl;
	}

	@Override
	public int compareTo(Movie movie) {
		long primaryKey = movie.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Movie)) {
			return false;
		}

		Movie movie = (Movie)object;

		long primaryKey = movie.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Movie> toCacheModel() {
		MovieCacheModel movieCacheModel = new MovieCacheModel();

		movieCacheModel.movieId = getMovieId();

		movieCacheModel.movieName = getMovieName();

		String movieName = movieCacheModel.movieName;

		if ((movieName != null) && (movieName.length() == 0)) {
			movieCacheModel.movieName = null;
		}

		movieCacheModel.directorName = getDirectorName();

		String directorName = movieCacheModel.directorName;

		if ((directorName != null) && (directorName.length() == 0)) {
			movieCacheModel.directorName = null;
		}

		movieCacheModel.yearReleased = getYearReleased();

		String yearReleased = movieCacheModel.yearReleased;

		if ((yearReleased != null) && (yearReleased.length() == 0)) {
			movieCacheModel.yearReleased = null;
		}

		movieCacheModel.actorName = getActorName();

		String actorName = movieCacheModel.actorName;

		if ((actorName != null) && (actorName.length() == 0)) {
			movieCacheModel.actorName = null;
		}

		return movieCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Movie, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Movie, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Movie, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Movie)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	//@Override
	public String toXmlString() {
		Map<String, Function<Movie, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Movie, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Movie, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Movie)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Movie>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Movie.class, ModelWrapper.class);

	}

	private long _movieId;
	private String _movieName;
	private String _directorName;
	private String _yearReleased;
	private String _actorName;

	public <T> T getColumnValue(String columnName) {
		Function<Movie, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Movie)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("movieId", _movieId);
		_columnOriginalValues.put("movieName", _movieName);
		_columnOriginalValues.put("directorName", _directorName);
		_columnOriginalValues.put("yearReleased", _yearReleased);
		_columnOriginalValues.put("actorName", _actorName);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("movieId", 1L);

		columnBitmasks.put("movieName", 2L);

		columnBitmasks.put("directorName", 4L);

		columnBitmasks.put("yearReleased", 8L);

		columnBitmasks.put("actorName", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Movie _escapedModel;

}